packages:
  - packages/*

catalog:
  "@rajzik/oxfmt-config": 4.0.1
  "@rajzik/oxlint-config": 4.0.1
  oxfmt: 0.45.0
  oxlint: 1.61.0
  oxlint-tsgolint: 0.21.1
  vitest: 4.1.4

catalogMode: prefer

ignoreWorkspaceRootCheck: true

linkWorkspacePackages: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - rajzik-theme
  - '@vscode/vsce'
  - '@rajzik/oxfmt-config'
  - '@rajzik/oxlint-config'
  - '@rajzik/configs-shared'

savePrefix: ''
